### ISSUE TITLE
Point cloud shader

### ISSUE THREAD

**Issue by StevieGoodman** [CMP2804/Assessment2#11]
# Summary
In order to communicate the topology of the environment, a point cloud should be used.
The player can use this to navigate the player character around the environment safely.

## Subtasks
- [x] Point generation
- [x] Point decay
- [x] Sound sources

# Intended outcome
- The player should be able to press a key to create a quiet noise
- The player should be able to press a key to create a loud noise
- When a noise is created, it should cause points to be generated in a spherical area centred around the source of the sound when a surface is encountered
- The magnitude of points should decrease with distance from the source
- The magnitude of points should decay with time

**Comment by Vesper-Works** [comment]
I've finished everything apart from the "press a key to create a x noise", since I'm not handling player input, but I've created a singleton class with the static method "MakeSound" which will let you implement that on the player controller.
